/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AdminRequestBuilderNavigationMetadata, AdminRequestBuilderRequestsMetadata, type AdminRequestBuilder } from './admin/index.js';
// @ts-ignore
import { InteractionHistoryRequestBuilderNavigationMetadata, InteractionHistoryRequestBuilderRequestsMetadata, type InteractionHistoryRequestBuilder } from './interactionHistory/index.js';
// @ts-ignore
import { RetrievalRequestBuilderRequestsMetadata, type RetrievalRequestBuilder } from './retrieval/index.js';
// @ts-ignore
import { type UsersRequestBuilder, UsersRequestBuilderNavigationMetadata, UsersRequestBuilderRequestsMetadata } from './users/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /copilot
 */
export interface CopilotRequestBuilder extends BaseRequestBuilder<CopilotRequestBuilder> {
    /**
     * Provides operations to manage the admin property of the microsoft.graph.copilotRoot entity.
     */
    get admin(): AdminRequestBuilder;
    /**
     * Provides operations to manage the interactionHistory property of the microsoft.graph.copilotRoot entity.
     */
    get interactionHistory(): InteractionHistoryRequestBuilder;
    /**
     * Provides operations to call the retrieval method.
     */
    get retrieval(): RetrievalRequestBuilder;
    /**
     * Provides operations to manage the users property of the microsoft.graph.copilotRoot entity.
     */
    get users(): UsersRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const CopilotRequestBuilderUriTemplate = "{+baseurl}/copilot";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CopilotRequestBuilderNavigationMetadata: Record<Exclude<keyof CopilotRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    admin: {
        requestsMetadata: AdminRequestBuilderRequestsMetadata,
        navigationMetadata: AdminRequestBuilderNavigationMetadata,
    },
    interactionHistory: {
        requestsMetadata: InteractionHistoryRequestBuilderRequestsMetadata,
        navigationMetadata: InteractionHistoryRequestBuilderNavigationMetadata,
    },
    retrieval: {
        requestsMetadata: RetrievalRequestBuilderRequestsMetadata,
    },
    users: {
        requestsMetadata: UsersRequestBuilderRequestsMetadata,
        navigationMetadata: UsersRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
