/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCopilotConversationCollectionResponseFromDiscriminatorValue, createCopilotConversationFromDiscriminatorValue, serializeCopilotConversation, type CopilotConversation, type CopilotConversationCollectionResponse } from '../../models/index.js';
// @ts-ignore
import { createODataErrorFromDiscriminatorValue, type ODataError } from '../../models/oDataErrors/index.js';
// @ts-ignore
import { CountRequestBuilderRequestsMetadata, type CountRequestBuilder } from './count/index.js';
// @ts-ignore
import { CopilotConversationItemRequestBuilderNavigationMetadata, CopilotConversationItemRequestBuilderRequestsMetadata, type CopilotConversationItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Provides operations to manage the conversations property of the microsoft.graph.copilotRoot entity.
 */
export interface ConversationsRequestBuilder extends BaseRequestBuilder<ConversationsRequestBuilder> {
    /**
     * Provides operations to count the resources in the collection.
     * @deprecated  as of 2025-03/PrivatePreview:copilotChatPrivatePreview1 on 2025-03-27 and will be removed 2025-08-28
     */
    get count(): CountRequestBuilder;
    /**
     * Provides operations to manage the conversations property of the microsoft.graph.copilotRoot entity.
     * @param copilotConversationId The unique identifier of copilotConversation
     * @returns {CopilotConversationItemRequestBuilder}
     * @deprecated  as of 2025-03/PrivatePreview:copilotChatPrivatePreview1 on 2025-03-27 and will be removed 2025-08-28
     */
     byCopilotConversationId(copilotConversationId: string) : CopilotConversationItemRequestBuilder;
    /**
     * The users conversations with Copilot Chat.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CopilotConversationCollectionResponse>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     * @deprecated  as of 2025-03/PrivatePreview:copilotChatPrivatePreview1 on 2025-03-27 and will be removed 2025-08-28
     */
     get(requestConfiguration?: RequestConfiguration<ConversationsRequestBuilderGetQueryParameters> | undefined) : Promise<CopilotConversationCollectionResponse | undefined>;
    /**
     * Create new navigation property to conversations for copilot
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CopilotConversation>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     * @deprecated  as of 2025-03/PrivatePreview:copilotChatPrivatePreview1 on 2025-03-27 and will be removed 2025-08-28
     */
     post(body: CopilotConversation, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CopilotConversation | undefined>;
    /**
     * The users conversations with Copilot Chat.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     * @deprecated  as of 2025-03/PrivatePreview:copilotChatPrivatePreview1 on 2025-03-27 and will be removed 2025-08-28
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<ConversationsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Create new navigation property to conversations for copilot
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     * @deprecated  as of 2025-03/PrivatePreview:copilotChatPrivatePreview1 on 2025-03-27 and will be removed 2025-08-28
     */
     toPostRequestInformation(body: CopilotConversation, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * The users conversations with Copilot Chat.
 */
export interface ConversationsRequestBuilderGetQueryParameters {
    /**
     * Include count of items
     */
    count?: boolean;
    /**
     * Expand related entities
     */
    expand?: string[];
    /**
     * Filter items by property values
     */
    filter?: string;
    /**
     * Order items by property values
     */
    orderby?: string[];
    /**
     * Search items by search phrases
     */
    search?: string;
    /**
     * Select properties to be returned
     */
    select?: string[];
    /**
     * Skip the first n items
     */
    skip?: number;
    /**
     * Show only the first n items
     */
    top?: number;
}
/**
 * Uri template for the request builder.
 */
export const ConversationsRequestBuilderUriTemplate = "{+baseurl}/copilot/conversations{?%24count,%24expand,%24filter,%24orderby,%24search,%24select,%24skip,%24top}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const ConversationsRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "count": "%24count",
    "expand": "%24expand",
    "filter": "%24filter",
    "orderby": "%24orderby",
    "search": "%24search",
    "select": "%24select",
    "skip": "%24skip",
    "top": "%24top",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ConversationsRequestBuilderNavigationMetadata: Record<Exclude<keyof ConversationsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byCopilotConversationId: {
        requestsMetadata: CopilotConversationItemRequestBuilderRequestsMetadata,
        navigationMetadata: CopilotConversationItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["copilotConversation%2Did"],
    },
    count: {
        requestsMetadata: CountRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ConversationsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ConversationsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCopilotConversationCollectionResponseFromDiscriminatorValue,
        queryParametersMapper: ConversationsRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: ConversationsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCopilotConversationFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCopilotConversation,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
