/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAiInteractionFromDiscriminatorValue, serializeAiInteraction, type AiInteraction } from '../../../../models/index.js';
// @ts-ignore
import { createODataErrorFromDiscriminatorValue, type ODataError } from '../../../../models/oDataErrors/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Provides operations to manage the interactions property of the microsoft.graph.aiInteractionHistory entity.
 */
export interface AiInteractionItemRequestBuilder extends BaseRequestBuilder<AiInteractionItemRequestBuilder> {
    /**
     * Delete navigation property interactions for copilot
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Get interactions from copilot
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AiInteraction>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     get(requestConfiguration?: RequestConfiguration<AiInteractionItemRequestBuilderGetQueryParameters> | undefined) : Promise<AiInteraction | undefined>;
    /**
     * Update the navigation property interactions in copilot
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AiInteraction>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     patch(body: AiInteraction, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<AiInteraction | undefined>;
    /**
     * Delete navigation property interactions for copilot
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Get interactions from copilot
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<AiInteractionItemRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Update the navigation property interactions in copilot
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPatchRequestInformation(body: AiInteraction, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Get interactions from copilot
 */
export interface AiInteractionItemRequestBuilderGetQueryParameters {
    /**
     * Expand related entities
     */
    expand?: string[];
    /**
     * Select properties to be returned
     */
    select?: string[];
}
/**
 * Uri template for the request builder.
 */
export const AiInteractionItemRequestBuilderUriTemplate = "{+baseurl}/copilot/interactionHistory/interactions/{aiInteraction%2Did}{?%24expand,%24select}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const AiInteractionItemRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "expand": "%24expand",
    "select": "%24select",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const AiInteractionItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: AiInteractionItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: AiInteractionItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createAiInteractionFromDiscriminatorValue,
        queryParametersMapper: AiInteractionItemRequestBuilderGetQueryParametersMapper,
    },
    patch: {
        uriTemplate: AiInteractionItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createAiInteractionFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeAiInteraction,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
