# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Strong names for .NET DLLs using ESRP

parameters:
  - name: projectName
    type: string
  - name: buildConfiguration
    type: string
    default: 'Release'

steps:
  - task: EsrpCodeSigning@5
    displayName: 'ESRP DLL Strong Name for ${{ parameters.projectName }}'
    inputs:
      ConnectedServiceName: 'Federated DevX ESRP Managed Identity Connection'
      AppRegistrationClientId: '65035b7f-7357-4f29-bf25-c5ee5c3949f8'
      AppRegistrationTenantId: 'cdc5aeea-15c5-4db6-b079-fcadd2505dc2'
      AuthAKVName: 'akv-prod-eastus'
      AuthCertName: 'ReferenceLibraryPrivateCert'
      AuthSignCertName: 'ReferencePackagePublisherCertificate'
      FolderPath: "$(Build.SourcesDirectory)/dotnet/src/${{ parameters.projectName }}/bin/${{ parameters.buildConfiguration }}/"
      Pattern: "**\\${{ parameters.projectName }}.dll"
      signConfigType: inlineSignParams
      UseMinimatch: true
      inlineOperation: |
        [
            {
                "keyCode": "CP-233863-SN",
                "operationSetCode": "StrongNameSign",
                "parameters": [],
                "toolName": "sign",
                "toolVersion": "1.0"
            },
            {
                "keyCode": "CP-233863-SN",
                "operationSetCode": "StrongNameVerify",
                "parameters": [],
                "toolName": "sign",
                "toolVersion": "1.0"
            }
        ]
      SessionTimeout: 20
      MaxConcurrency: 50
      MaxRetryAttempts: 5
      PendingAnalysisWaitTimeoutMinutes: 5
