[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "microsoft-agents-m365copilot-beta"
# The SDK version
# x-release-please-start-version
version = "1.0.0-preview.1"
# x-release-please-end
authors = [{name = "Microsoft", email = "graphtooling+ccspython@microsoft.com"}]
description = "The Microsoft CCS Python SDK"
dependencies = [
  "microsoft-kiota-bundle >=1.8.0,<2.0.0",
  "microsoft-kiota-authentication-azure >=1.8.0,<2.0.0",
]
requires-python = ">=3.9"
license = {file = "LICENSE"}
readme = "README.md"
keywords = ["copilot", "openAPI", "Microsoft"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: MIT License",
]

[project.optional-dependencies]
dev = ["yapf", "bumpver", "isort", "pylint", "pytest", "mypy"]

[project.urls]
homepage = "https://github.com/microsoft/Agents-M365Copilot/blob/main/python/README.md"
repository = "https://github.com/microsoft/Agents-M365Copilot/"
documentation = "https://github.com/microsoft/Agents-M365Copilot/blob/main/python/README.md"

[tool.flit.module]
name = "microsoft_agents_m365copilot_beta"

[tool.mypy]
warn_unused_configs = true
files = "microsoft_agents_m365copilot_beta"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "microsoft_agents_m365copilot_beta.generated"
ignore_errors = true

[tool.yapf]
based_on_style = "pep8"
dedent_closing_brackets = true
each_dict_entry_on_separate_line = true
column_limit = 100

[tool.isort]
profile = "hug"

[tool.pytest.ini_options]
pythonpath = [
  "microsoft_agents_m365copilot_beta"
]

[tool.bumpver]
current_version = "1.0.0"
version_pattern = "MAJOR.MINOR.PATCH[PYTAGNUM]"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = false
push = false

[tool.bumpver.file_patterns]
"pyproject.toml" = ['current_version = "{version}"', 'version = "{version}"']
"microsoft_agents_m365copilot_beta/_version.py" = ["{version}"]