/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCopilotSharePointRootFromDiscriminatorValue, type CopilotSharePointRoot } from '../../models/index.js';
// @ts-ignore
import { createODataErrorFromDiscriminatorValue, type ODataError } from '../../models/oDataErrors/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Provides operations to manage the sharePoint property of the microsoft.graph.copilotRoot entity.
 */
export interface SharePointRequestBuilder extends BaseRequestBuilder<SharePointRequestBuilder> {
    /**
     * Get sharePoint from copilot
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CopilotSharePointRoot>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     get(requestConfiguration?: RequestConfiguration<SharePointRequestBuilderGetQueryParameters> | undefined) : Promise<CopilotSharePointRoot | undefined>;
    /**
     * Get sharePoint from copilot
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<SharePointRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Get sharePoint from copilot
 */
export interface SharePointRequestBuilderGetQueryParameters {
    /**
     * Expand related entities
     */
    expand?: string[];
    /**
     * Select properties to be returned
     */
    select?: string[];
}
/**
 * Uri template for the request builder.
 */
export const SharePointRequestBuilderUriTemplate = "{+baseurl}/copilot/sharePoint{?%24expand,%24select}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const SharePointRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "expand": "%24expand",
    "select": "%24select",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const SharePointRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: SharePointRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCopilotSharePointRootFromDiscriminatorValue,
        queryParametersMapper: SharePointRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
