/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAiInteractionHistoryFromDiscriminatorValue, serializeAiInteractionHistory, type AiInteractionHistory } from "../../../../models/index.js";
// @ts-ignore
import { createODataErrorFromDiscriminatorValue, type ODataError } from "../../../../models/oDataErrors/index.js";
// @ts-ignore
import { GetAllEnterpriseInteractionsRequestBuilderRequestsMetadata, type GetAllEnterpriseInteractionsRequestBuilder } from "./getAllEnterpriseInteractions/index.js";
// @ts-ignore
import { InteractionsRequestBuilderNavigationMetadata, InteractionsRequestBuilderRequestsMetadata, type InteractionsRequestBuilder } from "./interactions/index.js";
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from "@microsoft/kiota-abstractions";

/**
 * Provides operations to manage the interactionHistory property of the microsoft.graph.aiUser entity.
 */
export interface InteractionHistoryRequestBuilder extends BaseRequestBuilder<InteractionHistoryRequestBuilder> {
	/**
	 * Provides operations to call the getAllEnterpriseInteractions method.
	 */
	get getAllEnterpriseInteractions(): GetAllEnterpriseInteractionsRequestBuilder;
	/**
	 * Provides operations to manage the interactions property of the microsoft.graph.aiInteractionHistory entity.
	 */
	get interactions(): InteractionsRequestBuilder;
	/**
	 * Delete navigation property interactionHistory for copilot
	 * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
	 * @throws {ODataError} error when the service returns a 4XX or 5XX status code
	 */
	delete(requestConfiguration?: RequestConfiguration<object> | undefined): Promise<void>;
	/**
	 * Get interactionHistory from copilot
	 * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
	 * @returns {Promise<AiInteractionHistory>}
	 * @throws {ODataError} error when the service returns a 4XX or 5XX status code
	 */
	get(requestConfiguration?: RequestConfiguration<InteractionHistoryRequestBuilderGetQueryParameters> | undefined): Promise<AiInteractionHistory | undefined>;
	/**
	 * Update the navigation property interactionHistory in copilot
	 * @param body The request body
	 * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
	 * @returns {Promise<AiInteractionHistory>}
	 * @throws {ODataError} error when the service returns a 4XX or 5XX status code
	 */
	patch(body: AiInteractionHistory, requestConfiguration?: RequestConfiguration<object> | undefined): Promise<AiInteractionHistory | undefined>;
	/**
	 * Delete navigation property interactionHistory for copilot
	 * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
	 * @returns {RequestInformation}
	 */
	toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined): RequestInformation;
	/**
	 * Get interactionHistory from copilot
	 * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
	 * @returns {RequestInformation}
	 */
	toGetRequestInformation(requestConfiguration?: RequestConfiguration<InteractionHistoryRequestBuilderGetQueryParameters> | undefined): RequestInformation;
	/**
	 * Update the navigation property interactionHistory in copilot
	 * @param body The request body
	 * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
	 * @returns {RequestInformation}
	 */
	toPatchRequestInformation(body: AiInteractionHistory, requestConfiguration?: RequestConfiguration<object> | undefined): RequestInformation;
}
/**
 * Get interactionHistory from copilot
 */
export interface InteractionHistoryRequestBuilderGetQueryParameters {
	/**
	 * Expand related entities
	 */
	expand?: string[];
	/**
	 * Select properties to be returned
	 */
	select?: string[];
}
/**
 * Uri template for the request builder.
 */
export const InteractionHistoryRequestBuilderUriTemplate = "{+baseurl}/copilot/users/{aiUser%2Did}/interactionHistory{?%24expand,%24select}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const InteractionHistoryRequestBuilderGetQueryParametersMapper: Record<string, string> = {
	expand: "%24expand",
	select: "%24select",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const InteractionHistoryRequestBuilderNavigationMetadata: Record<Exclude<keyof InteractionHistoryRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
	getAllEnterpriseInteractions: {
		requestsMetadata: GetAllEnterpriseInteractionsRequestBuilderRequestsMetadata,
	},
	interactions: {
		requestsMetadata: InteractionsRequestBuilderRequestsMetadata,
		navigationMetadata: InteractionsRequestBuilderNavigationMetadata,
	},
};
/**
 * Metadata for all the requests in the request builder.
 */
export const InteractionHistoryRequestBuilderRequestsMetadata: RequestsMetadata = {
	delete: {
		uriTemplate: InteractionHistoryRequestBuilderUriTemplate,
		responseBodyContentType: "application/json",
		errorMappings: {
			XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
		},
		adapterMethodName: "sendNoResponseContent",
	},
	get: {
		uriTemplate: InteractionHistoryRequestBuilderUriTemplate,
		responseBodyContentType: "application/json",
		errorMappings: {
			XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
		},
		adapterMethodName: "send",
		responseBodyFactory: createAiInteractionHistoryFromDiscriminatorValue,
		queryParametersMapper: InteractionHistoryRequestBuilderGetQueryParametersMapper,
	},
	patch: {
		uriTemplate: InteractionHistoryRequestBuilderUriTemplate,
		responseBodyContentType: "application/json",
		errorMappings: {
			XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
		},
		adapterMethodName: "send",
		responseBodyFactory: createAiInteractionHistoryFromDiscriminatorValue,
		requestBodyContentType: "application/json",
		requestBodySerializer: serializeAiInteractionHistory,
		requestInformationContentSetMethod: "setContentFromParsable",
	},
};
/* tslint:enable */
/* eslint-enable */
