# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Build, package, and deploy TypeScript package for @microsoft/agents-m365copilot

name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'typescript/packages/agents-m365copilot/generated/**'
  tags:
    include:
      - '@microsoft/agents-m365copilot-v1*'

pr: none

variables:
  package_name_v1: 'agents-m365copilot'
  package_dir_v1: 'packages/agents-m365copilot'

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      vmImage: windows-latest
    stages:

    - stage: build
      displayName: 'Build and Package V1 TypeScript Package'
      # This condition allows the build to run for both tagged builds and manual builds.
      condition: or(contains(variables['Build.SourceBranch'], '@microsoft/agents-m365copilot-v1'), eq(variables['Build.Reason'], 'Manual'))
      jobs:
        - job: build_typescript
          displayName: 'Build, Test, and Package V1'
          pool:
            name: Azure-Pipelines-1ESPT-ExDShared
            vmImage: ubuntu-latest

          steps:
            - task: UseNode@1
              displayName: 'Install Node.js'
              inputs:
                version: '22.x'
            - script: npm ci
              displayName: 'Install npm dependencies'
              workingDirectory: '$(Build.SourcesDirectory)/typescript/'

            # Build V1 TypeScript package
            - script: npm run build --workspace=$(package_dir_v1)
              displayName: 'Build $(package_name_v1)'
              workingDirectory: '$(Build.SourcesDirectory)/typescript/'

            - script: npm pack --workspace=$(package_dir_v1) --pack-destination=$(Build.SourcesDirectory)/typescript/$(package_dir_v1)
              displayName: 'Generate npm package $(package_name_v1)'
              workingDirectory: '$(Build.SourcesDirectory)/typescript'
              
            # Stage artifacts for V1 package

            - task: CopyFiles@2
              inputs:
                sourceFolder: '$(Build.SourcesDirectory)/typescript/$(package_dir_v1)'
                targetFolder: '$(Build.ArtifactStagingDirectory)/npm/$(package_name_v1)'
                Contents: |
                  microsoft-agents-m365copilot-v1*.tgz
              displayName: "Copy npm package files for $(package_name_v1)"

          templateContext:
            outputs:
              - output: pipelineArtifact
                displayName: 'Stage V1 TypeScript package artifacts'
                artifactName: npm_$(package_name_v1)
                targetPath: '$(Build.ArtifactStagingDirectory)/npm/$(package_name_v1)'
                condition: or(contains(variables['Build.SourceBranch'], '@microsoft/agents-m365copilot-v1'), eq(variables['Build.Reason'], 'Manual'))
                # Build.SourceBranch expands to 'refs/tags/@microsoft/agents-m365copilot-v1-v0.1.0-preview.0'

    - stage: deploy
      displayName: 'Deploy V1 NPM Package'
      dependsOn: build
      # This condition allows the build to run for only tagged builds. Manual runs are temp and should be removed after validation.
      condition: or(and(contains(variables['Build.SourceBranch'], '@microsoft/agents-m365copilot-v1'), succeeded()), eq(variables['Build.Reason'], 'Manual'))
      jobs:
        - deployment: publish_npm_package
          displayName: 'Publish npm Package'
          environment: agents-m365copilot-prod
          pool:
            name: Azure-Pipelines-1ESPT-ExDShared
            image: ubuntu-latest
            os: linux

          templateContext:
              type: releaseJob
              isProduction: true
              inputs:
                - input: pipelineArtifact
                  artifactName: npm_$(package_name_v1)
                  targetPath: '$(Build.ArtifactStagingDirectory)/npm'
          strategy:
            runOnce:
              deploy:
                steps:    
                - task: EsrpRelease@9
                  displayName: 'Publish V1 NPM package via ESRP Release'
                  inputs:
                    connectedservicename: "Federated DevX ESRP Managed Identity Connection"
                    usemanagedidentity: false
                    keyvaultname: 'akv-prod-eastus'
                    authcertname: 'ReferenceLibraryPrivateCert'
                    signcertname: 'ReferencePackagePublisherCertificate'
                    clientid: '65035b7f-7357-4f29-bf25-c5ee5c3949f8'
                    intent: 'PackageDistribution'
                    contenttype: 'npm'
                    contentsource: 'Folder'
                    folderlocation: '$(Build.ArtifactStagingDirectory)/npm'
                    owners: 'mmainer@microsoft.com,gavinbarron@microsoft.com'
                    approvers: 'mmainer@microsoft.com,christiano@microsoft.com,gavinbarron@microsoft.com,lramosvea@microsoft.com'
                    serviceendpointurl: 'https://api.esrp.microsoft.com'
                    mainpublisher: 'ESRPRELPACMAN'
                    domaintenantid: 'cdc5aeea-15c5-4db6-b079-fcadd2505dc2'